import "@/app/[locale]/ui/globals.css";
import BaseLayout from "@/components/ui/base-layout";
import { routing } from "@/i18n/routing";
import type { Metadata } from "next";
import { notFound } from "next/navigation";

export const metadata: Metadata = {
	title: {
		template: "%s | Bocal",
		default: "Bocal",
	},
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
}>): Promise<React.JSX.Element> {
	const locale = (await params).locale;

	// biome-ignore lint/suspicious/noExplicitAny: locale exception.
	if (!routing.locales.includes(locale as any)) {
		notFound();
	}

	return <BaseLayout locale={locale}>{children}</BaseLayout>;
}
